name: youtube_player_iframe_example
description: Demonstrates how to use the youtube_plyr_iframe plugin.
version: 2.0.7
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  youtube_plyr_iframe:
    path: ../

flutter:
  uses-material-design: true
