name: youtube_plyr_iframe
description: Fork of Youtube Player Iframe. Supports web & mobile platforms.
version: 2.0.4-pre.1
repository: https://github.com/jonatadashi/youtube_plyr_iframe
homepage: https://github.com/jonatadashi/youtube_plyr_iframe

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.2'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ">=5.3.2 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
