name: youtube_plyr_iframe
description: Fork of Youtube Player Iframe. Supports web & mobile platforms.
version: 2.0.3-rc.2
repository: https://github.com/jonatadashi/youtube_plyr_iframe
homepage: https://github.com/jonatadashi/youtube_plyr_iframe

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: ">=5.2.1+1 <6.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter