name: youtube_plyr_iframe
description: Fork of Youtube Player Iframe. Supports web & mobile platforms.
version: 1.3.6+1
repository: https://github.com/jonatadashi/youtube_plyr_iframe
homepage: https://github.com/jonatadashi/youtube_plyr_iframe

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_inappwebview: '>=5.0.4-nullsafety.1 <6.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter